framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://redis:6379

        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

services:
    _defaults:
        autowire: true
        autoconfigure: true

    cache.default_marshaller:
        class: Symfony\Component\Cache\Marshaller\DefaultMarshaller
        arguments:
            $useIgbinarySerialize: true
