framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: 'roadrunner://'
                options:
                    queue_name: async

            failed: 'in-memory://'

        routing:
            'App\Message\CommentCreateMessage': async

services:
    _defaults:
        autowire: true
        autoconfigure: true

    messenger.transport.roadrunner.factory:
        class: Roqmeu\Symfony\Messenger\Bridge\RoadRunner\Transport\RoadRunnerTransportFactory
        tags: [ messenger.transport_factory ]
