monolog:
    channels:
        - deprecation
    handlers:
        main:
            type: stream
            path: php://stderr
            level: notice
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
