version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  pool:
    debug: false
    max_jobs: 1000
    num_workers: 4
  middleware: [ "gzip" ]

logs:
  mode: production
  level: warn
  channels:
    http:
      level: warn # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw

# Uncomment to use metrics integration
# rpc:
#   listen: tcp://127.0.0.1:6001

# Uncomment to use metrics integration
# metrics:
#   # prometheus client address (path /metrics added automatically)
#   address: "0.0.0.0:9180"
