version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

rpc:
  listen: unix:///var/www/rr.sock

http:
  address: 0.0.0.0:8080
  pool:
    debug: false
    max_jobs: 100000
    num_workers: 4
    supervisor:
      watch_tick: 5s
      max_worker_memory: 128
  middleware: [ "gzip" ]

logs:
  mode: production
  level: warn
  channels:
    http:
      level: warn # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw

amqp:
  addr: amqp://rabbitmq:5672

jobs:
  num_pollers: 1
  consume: [ "async" ]
  pipelines:
    async:
      driver: amqp
      config:
        queue: symfony-demo.async
        exchange: symfony-demo
        exchange_type: direct
        routing_key: symfony-demo.async
  pool:
    debug: false
    num_workers: 1
    command: "bin/console messenger:consume async --silent"

# Uncomment to use metrics integration
# rpc:
#   listen: tcp://127.0.0.1:6001

# Uncomment to use metrics integration
# metrics:
#   # prometheus client address (path /metrics added automatically)
#   address: "0.0.0.0:9180"
