FROM docker.angie.software/angie:1.8.3-alpine

LABEL "org.opencontainers.image.source"="https://github.com/roqmeu/symfony-roadrunner-workshop-2025-04"

COPY ./deploy/nginx/angie.conf /etc/angie/angie.conf
